## Numpy

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
np.__version__

'1.15.4'

In [8]:
a=np.array(range(5,10))
print(a)
print(type(a))

[5 6 7 8 9]
<class 'numpy.ndarray'>


In [18]:
print(a.shape)  #tuple
print(a.dtype)
print(a.size)
print(a.itemsize) # no of bytes foe each item
print(a.ndim)

(4,)
int8
4
1
1


In [11]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print(a1.shape)  #tuple
print(a1.dtype)
print(a1.size)
print(a1.itemsize) # no of bytes foe each item
print(a1.ndim)

(3, 3)
int32
9
4
2


In [13]:
print(a1.shape[0]) # no of rows

3


In [14]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [17]:
a=np.array([1,2,3,7],dtype=np.int8)
a

array([1, 2, 3, 7], dtype=int8)

In [19]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.diag([2,3])

array([[2, 0],
       [0, 3]])

In [31]:
np.full([2,4],3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [32]:
np.arange(2,6)

array([2, 3, 4, 5])

In [33]:
np.arange(2,15,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [34]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [36]:
a=np.arange(5)
b=np.ones(5)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)

[1. 2. 3. 4. 5.]
[-1.  0.  1.  2.  3.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 0. 0. 0. 0.]
[-0.  1.  2.  3.  4.]


In [38]:
print(a*2)
print(a**2)
print(a+2)
print(a-2)
print(a//2)

[0 2 4 6 8]
[ 0  1  4  9 16]
[2 3 4 5 6]
[-2 -1  0  1  2]
[0 0 1 1 2]


## Random

In [41]:
np.random.randint(100)

62

In [43]:
np.random.randint(100,size=6)

array([87, 39,  6, 26, 58, 54])

In [44]:
np.random.randint(100,size=(6,3))

array([[26, 45, 95],
       [79, 91,  6],
       [ 7, 36, 73],
       [79,  7, 48],
       [98, 81, 64],
       [62, 28, 61]])

In [45]:
np.random.random()

0.696966251777131

In [46]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [48]:
np.random.random((2,3)) # If we use random the value should be goiven in tuple

array([[0.70036826, 0.34760221, 0.17841727],
       [0.55056622, 0.58591408, 0.959288  ]])

In [49]:
np.random.rand(2,3) #If we use rand no need of tuple

array([[0.37644834, 0.96121162, 0.47053586],
       [0.30202121, 0.74965935, 0.47498078]])

In [50]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [52]:
r=np.arange(10,20)
np.random.shuffle(r)
print(r)

[13 15 10 11 18 17 12 14 19 16]


## Array Manipulation

In [53]:
a=np.arange(20)
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [54]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
a.reshape(20,1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [56]:
a.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [57]:
np.resize(a,(13,2))  #if we use numpy for resize it will again fill from strating for remaimimg values

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [62]:
z=np.arange(20)
z.resize((13,2))
z                   #If we use resize with var reamining values are filled with 0's

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

In [71]:
np.expand_dims(a,0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [68]:
np.expand_dims(a,0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [73]:
np.expand_dims(a,0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [74]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
z.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  0,  0,  0,  0,  0,  0])

In [76]:
for i in a:
    print(i)
    break

0


In [77]:
a1=np.array([[1,2,3],[4,5,6]])

In [78]:
for i in a1:
    print(i)
    break

[1 2 3]


In [83]:
a2=np.arange(12).reshape(2,2,3)
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [85]:
for i in a2:
    print(i)
    break
    

[[0 1 2]
 [3 4 5]]


In [86]:
print(a[[1,10,3]])

[ 1 10  3]


## Fancy indexing

In [87]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [88]:
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [89]:
a1%2==0

array([[False,  True, False],
       [ True, False,  True]])

In [90]:
a2%2==0

array([[[ True, False,  True],
        [False,  True, False]],

       [[ True, False,  True],
        [False,  True, False]]])

In [91]:
a1[0]

array([1, 2, 3])

In [95]:
a2[1][1]


array([ 9, 10, 11])

In [96]:
a2[1][0]

array([6, 7, 8])

In [98]:
a1[[1,0]]

array([[4, 5, 6],
       [1, 2, 3]])