### Hacker rank problems

#### 1. To Print Hello, World! to stdout.

In [1]:
if __name__ == '__main__':
    print("Hello, World!")

Hello, World!


#### 2. Arithmetic Operators

- Input:
    - 2
    - 3
- Output:
    - 5
    - -1
    - 6

In [3]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)

2
3
5
-1
6


#### 3. Divisions

- Input:
    - 10
    - 3
- Output:
    - 3
    - 3.3333333333335

In [4]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    c=a//b
    print(c)
    c=a/b
    print(c)

10
3
3
3.3333333333333335


#### 4. Loop to print the squares 

- Input:
    - 5
- Output:
    - 0
    - 1
    - 4
    - 9
    - 16

In [6]:
if __name__ == '__main__':
    n = int(input())
    for i in range(0,n):
       print(i*i)

5
0
1
4
9
16


#### 5. print function

- Input:
    - 5
- Output:
    - 12345

In [7]:
if __name__ == '__main__':
    n = int(input())
    for i in range(1,n+1):
        print(i,end='')

5
12345

#### 6. if- else

- Input:
    - 5
- Output:
    - Weird

In [6]:
#!/bin/python3
import math
import os
import random
import re
import sys
if __name__ == '__main__':
    n = int(input().strip())
    if(n%2!=0):
        print("Weird")
    else:
        if(2<=n<=5 or n>20):
            print("Not Weird")
        else:
            print("Weird")      

5
Weird


#### 7. Leap year using functions

- Input:
    - 2020
- Output:
    - True

In [8]:
def is_leap(year):
    return (year%4==0 and (year%100!=0 or year%400==0))
 
year = int(input())
print(is_leap(year))

2020
True


#### 8. To print the name using strings

- Input:
    - kavya
    - sree
- Output:
    - Hello kavya sree! You just delved into python.

In [7]:
def print_full_name(a, b):
    print("Hello "+a+ " "+b+"! You just delved into python.")

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

kavya
sree
Hello kavya sree! You just delved into python.


#### 9.  Tuples

- Input:
    - 2
    - 1 2
- Output:
    - 3430014387543 (hash of tuple)

In [2]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    t=tuple(integer_list)
    print(hash(t))

2
12
3430014387543


#### 10. Find the Runner-Up Score!

- Input:
    - 5
    - 2 3 6 6 5
- Output:
    - 5

In [4]:
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    z=max(arr)
    while(max(arr)==z):
        arr.remove(max(arr))
    print(max(arr))

5
2 3 6 6 5
5


#### 11. Swap-Case

- Input:
    - KAvYa SrEE
- Output:
    - kaVyA sRee

In [9]:
import string
def swap_case(s):
    return s.swapcase()

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

KAvYa SrEE
kaVyA sRee


#### 12. Mutations in strings

- Input:
    - kavyasree
    - 5 b
- Output:
    - kavyabree

In [11]:
def mutate_string(string, position, character):
    str=string[:position]+character+string[position+1:]
    return str

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

kavyasree
5 b
kavyabree


#### 12. Split and join

- Input:
    - kavya sree
- Output:
    - kavya-sree

In [12]:
def split_and_join(line):
    # write your code here
    line=line.split(" ")
    line="-".join(line)
    return line

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

kavya sree
kavya-sree


#### 13. Shape

- Input:
    - 1 2 3 4 5 6 7 8 9
- Output:
    - [[1 2 3]<br>
      [4 5 6]<br>
      [7 8 9]]

In [16]:
import numpy as np
print(np.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 14. List comprehension

- Input:
    - 1<br>
    1<br>
    1<br>
    2
- Output:
    - [[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]

In [4]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    print ([[a,b,c] for a in range(0,x+1) for b in range(0,y+1) for c in range(0,z+1) if a + b + c != n ])

1
1
1
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


#### 15. Nested Lists(second lowest grade)

- Input:
    - 4 <br>
     Harry<br>
     37.21 <br>
     Berry <br>
     37.21 <br>
     Tina<br>
     37.2<br>
     Akriti<br>
     41
     
- Output:
    - Berry<br>
      Harry

In [2]:
score_list = []
mark_sheet=[]
for _ in range(int(input())):
    name = input()
    score = float(input())
    mark_sheet.append([name,score])
    score_list.append(score)
second_lowest_mark = sorted(list(dict.fromkeys(score_list)))[1]
for name,marks in sorted(mark_sheet):
    if marks == second_lowest_mark:
        print(name)

3
kavya
2
jyothi
1
ramya
3
kavya


#### 16. Reduce function

- Input:
    -3 <br>
    1 2<br>
    3 4<br>
    10 6
- Output:
    - 5 8

In [23]:
from fractions import Fraction
from functools import reduce
import operator
def product(fracs):
    t = reduce(operator.mul , fracs)
    return t.numerator, t.denominator

if __name__ == '__main__':
    fracs = []
    for _ in range(int(input())):
        fracs.append(Fraction(*map(int, input().split())))
    result = product(fracs)
    print(*result)

3
1 2
3 4
10 6
5 8


#### 17. String Validation

- Input:
    - qA2
- Output:
    - True<br>
    True<br>
    True<br>
    True<br>
    True

In [10]:
str = input()
print(any(c.isalnum() for c in str))
print(any(c.isalpha() for c in str))
print(any(c.isdigit() for c in str))
print(any(c.islower() for c in str))
print(any(c.isupper() for c in str))

qA2
True
True
True
True
True


#### 18. Finding the percentage

- Input:
    - 2 <br>
    kavya 30 29 28<br>
    jyothi 30 30 29<br>
    kavya
- Output:
    - 29.00

In [3]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    query_scores = student_marks[query_name]
    print("{0:.2f}".format(sum(query_scores)/(len(query_scores))))

2
kavya 30 29 28
jyothi 30 30 29
kavya
29.00


#### 19. Find the average in sets

- Input:
    - 10<br>
    4 6 8 4 7 4 8 6 2 5
- Output:
    - 5.333333333333333

In [12]:
def average(array):
    # your code goes here
    array=set(array)
    avg=sum(array)/len(array)
    return avg

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
4 6 8 4 7 4 8 6 2 5
5.333333333333333


#### 20. Happiness

- Input:
    - 3 2<br>
    1 5 3<br>
    3 1<br>
    5 7
- Output:
    - 1

In [16]:
x=input()
n,m=map(int,x.split())
x=input()
l=list(map(int,x.split()))
x=input()
a=list(map(int,x.split()))
x=input()
b=list(map(int,x.split()))
a=set(a)
b=set(b)
happiness=0
for x in range(n):
    if l[x] in a:
        happiness+=1
for x in range(n):
    if l[x] in b:
        happiness-=1
print(happiness)

3 2
1 5 3
3 1
5 7
1


#### 21. Symmetric Difference

- Input:
    - 4<br>
    2 4 5 9<br>
    4<br>
    2 4 11 12
- Output:
    - 5<br>
    9<br>
    11<br>
    12

In [18]:
na=int(input())
a=input()
nb=int(input())
b=input()
la=list(map(int,a.split()))
lb=list(map(int,b.split()))
la=set(la)
lb=set(lb)
diff=la.symmetric_difference(lb)
diff=list(diff)
diff.sort()
for i in diff:
     print(i)


4
2 4 5 9
4
2 4 11 12
5
9
11
12


#### 22. Calendar

- Input:
    - 27 05 1998
- Output:
    - WEDNESDAY

In [21]:
import datetime 
import calendar 
  
def findDay(date): 
    data= datetime.datetime.strptime(date, '%d %m %Y').weekday() 
    return (calendar.day_name[data]) 
  
date = input()
print(findDay(date)) 

27 05 1998
Wednesday
